#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#home:
#  path: /
#  controller: App\Controller\HomeController::index

#computer_index:
#  path: /computer
#  controller: App\Controller\ComputerController::index